import Link from "next/link";

import { SITE } from "@/lib/site";

export function ResultBanner({ kind }: { kind: "audit" | "roast" }) {
  const href = kind === "audit" ? "/audit" : "/roast";
  const label = kind === "audit" ? "Get your own free audit" : "Roast your own outreach";
  return (
    <div className="mt-12 rounded-2xl border border-neutral-800 bg-neutral-950 p-6 text-center sm:p-8">
      <p className="text-lg font-medium text-white">Generated by an AI agent, in seconds.</p>
      <p className="mx-auto mt-2 max-w-md text-[14px] leading-relaxed text-neutral-400">
        This is a live demo of what {SITE.name} builds. Run your own, free.
      </p>
      <div className="mt-5 flex flex-wrap items-center justify-center gap-3">
        <Link
          href={href}
          className="inline-flex items-center justify-center rounded-full bg-sky-400 px-5 py-2.5 text-sm font-medium text-neutral-950 transition-colors hover:bg-sky-300"
        >
          {label} →
        </Link>
        <a
          href={SITE.calUrl}
          target="_blank"
          rel="noreferrer"
          className="inline-flex items-center justify-center rounded-full border border-neutral-700 px-5 py-2.5 text-sm font-medium text-neutral-200 transition-colors hover:border-neutral-500 hover:text-white"
        >
          Book a call
        </a>
      </div>
    </div>
  );
}
